name = "Severus"
uuid = "dfc6c722-4af6-47a0-a997-48b85eeeb58b"
authors = ["chethana-rao <chethanaprao@alumni.iitm.ac.in>"]
version = "0.1.0"

[deps]
Comodo = "59095408-2761-4f7a-bdc2-044e78630271"

[compat]
Comodo = "0.1.0"
